version: '3.8'  

services:
  postgres:
    container_name: desafio-shopper-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio-shopper
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

